name: C tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-2004:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install make gcc
    - name: Build
      run: make -Clotordb/src

  build-2204:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install make gcc
    - name: Build
      run: make -Clotordb/src

  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install make gcc
    - name: Build
      run: make -Clotordb/src
